server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  h2:
    console:
      enabled: true
